stages:
- name: Publish Flask image
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: app/${CICD_GIT_REPO_NAME}-web:latest
      pushRemote: true
      registry: 127.0.0.1:34840
- name: Deploy app-web-test1
  steps:
  - applyAppConfig:
      catalogTemplate: cattle-global-data:iii-devops-web
      version: 0.1.0
      answers:
        web.image: 127.0.0.1:34471/${CICD_GIT_REPO_NAME}-web
        web.type: uwsgi-flask
      name: ${CICD_GIT_REPO_NAME}-${CICD_GIT_BRANCH}-app-web-test1
      targetNamespace: p-v2nzs-pipeline
- name: Deploy app-web-test2
  steps:
  - applyAppConfig:
      catalogTemplate: cattle-global-data:iii-devops-web
      version: 0.1.0
      answers:
        web.image: 127.0.0.1:34471/${CICD_GIT_REPO_NAME}-web
        web.type: uwsgi-flask
      name: ${CICD_GIT_REPO_NAME}-${CICD_GIT_BRANCH}-app-web-test2
      targetNamespace: p-v2nzs-pipeline
notification: {}
